### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" when running docker build

### ISSUE THREAD

**Issue by saviola777** [joernhees/userdocker#11]
If there's a `docker build` container running, I am getting the above error for commands like `userdocker run` and `userdocker ps --gpu-free`, in the line 

```
for dev in devs:
```

in `userdocker/helpers/nvidia.py`, presumably caused by the output of `docker inspect` being different than expected for containers created during `docker build`. My [quick & dirty solution](https://github.com/saviola777/userdocker/blob/c79df369246225ab1f012b20caac4f59c97e514f/userdocker/helpers/nvidia.py) was to skip containers where no devs were found.

**Comment by joernhees** [comment]
this should be fixed with dd061bd8b6908c9961e522059dd511069a166b39 ... `inspect` proved to be more unreliable than intended, so we're now depending on own env-vars. In case more memory of a GPU is used by docker build, the GPU should be excluded by `NV_GPU_UNAVAILABLE_ABOVE_MEMORY_USED`

reopen if still a problem
