### ISSUE TITLE
Documentation on creation of user/group within container

### ISSUE THREAD

**Issue by saviola777** [joernhees/userdocker#5]
By default, the user/group of the calling user is taken over inside the container, but neither the user or group exists in the container:

```
sudo userdocker run -t -i -v $HOME:$HOME debian bash                                               
INFO:userdocker:executing command: /usr/bin/docker run --rm -t -i -v /home/saviola:/home/saviola -e HOME=/home/saviola -e USERDOCKER=2.0.0 -e USERDOCKER_USER=saviola -e USERDOCKER_UID=1000 -u 1000:1000 --cap-drop=ALL debian:latest bash
[I have no name!@e438324053fb /]$ whoami                                                                               
whoami: cannot find name for user ID 1000
```

Since this is something every user of userdocker will have to deal with, maybe you could add information on the (automatic) creation of user/groups in containers in the documentation?

**Comment by joernhees** [comment]
Yes, i thought about that for a while...

IMO implicitly creating users / groups inside the containers will cause more problems than leaving this to admins (e.g. by `-v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro`). The reason is that on many cluster systems the necessary info is not contained in `/etc/{passwd,groups}` but some ldap and there are no "up-to-date" files you can easily mount. Generating them temporarily might cause them to be out of sync and might be dangerous.

Hence, for now my decision there was not to fiddle with any of that at the cost of mostly cosmetic problems such as the "I have no name" and `whoami`. If you work on mounted host dirs, your uid and gid will ensure that the files look correct on the host though.

I'll add a comment to `default.py`

**Comment by saviola777** [comment]
Thanks, didn't consider simply mounting the group/passwd files inside the containers, that might already solve the problem (for me).

**Comment by malteos** [comment]
When running `-v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro` I get the following error:

```
ERROR: given mount not allowed: /etc/passwd:/etc/passwd:ro
```

Is there any other way to solve the missing user/group issue?

**Comment by saviola777** [comment]
You need to include the mounts in your config file. I'm not sure if there is any other way.
