### ISSUE TITLE
Adding the build subcommand

### ISSUE THREAD

**Issue by saviola777** [joernhees/userdocker#6]
tl;dr: Would you consider adding the `build` subcommand (or accept a PR adding the `build` subcommand), or is this something you have left out on purpose?

We would like to allow our users to build docker images from their Dockerfiles, and the simplest solution seems to be adding the `build` subcommand to userdocker. I'm not too familiar with docker yet, so maybe I'm missing some problematic implication of allowing users to build their own docker images (still, the subcommand could be added and disabled by default)?

**Comment by joernhees** [comment]
I felt that adding `userdocker build` has severe security implications as `docker build` runs with root permissions on the host system (and thereby can read things from there that normal users cannot).

Think of something like `userdocker build -f $HOME/DockerfileSnoop /root/ -t snoop_root_secrets` with `$HOME/DockerfileSnoop` like this:

```
FROM debian
ADD . /secrets
RUN chmod -R a+rx /secrets
```

After discussing this in our group, we didn't see an easy, fool-proof way to restrict 2 things there:
1. root read access to host files (e.g. via `ADD`, `COPY`...)
2. dropping root privileges inside the container (e.g. for `RUN` commands as the above)

That's why i decided to leave it out for now and rather suggest to allow pulling external images. I'd even go as far and say that allowing to pull any image from any registry is probably safer from an admin perspective than allowing users to build on a host on which they shouldn't be root.

If you see a way around these issues, i'd be happy to re-consider adding `build` support.

(Note how `userdocker load` also doesn't include the `-i` option for the same reasons.)

**Comment by saviola777** [comment]
Thanks for your detailed explanation. You are correct of course, I did not consider these problems. I'll close this for now.
