### ISSUE TITLE
Arguments with options for ARGS_ALWAYS

### ISSUE THREAD

**Issue by saviola777** [joernhees/userdocker#8]
It would be nice to be able to specify arguments with options in ARGS_ALWAYS (e.g. something like `--cpus="1"` for the `run` subcommand). Are there any plans to support something like that in the future, or any problems that would make this difficult / problematic? Thanks.

**Comment by joernhees** [comment]
hmm, currently only "flags" (args without options as you call it) are supported in `ARGS_ALWAYS` and `ARGS_AVAILABLE`. The reason is that their handling is uniform as they don't need any rules for the value. Also currently we make use of this fact to actually allow users to specify flags that are in `ARGS_ALWAYS` on commandline again. For that with everything but flags we'd probably need special handling, especially for cases where we have further handling in the specific subcommand parsers...

So minor difficulties / problems: yes.

However, i can see that admins might want to require certain arg-value combinations, so allowing them in `ARGS_ALWAYS` is probably a good idea.

**Comment by saviola777** [comment]
Well, thanks… I guess your solution is more elegant than mine. :)

**Comment by joernhees** [comment]
😬 big sorry, seem to have missed the notification on on this and unintentionally quickly implemented it myself when we urgently needed the feature without rechecking the issues here :-/

**Comment by saviola777** [comment]
No worries!
